services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

  ingest_yellow:
      image: taxi_ingest:v001
      depends_on:
        - pgdatabase
      command: >
        ingest_data.py
        --pg-user=root
        --pg-pass=root
        --pg-host=pgdatabase
        --pg-port=5432
        --pg-db=ny_taxi
        --target-table=yellow_taxi_trips
      profiles:
        - ingest

  ingest_zones:
      image: taxi_ingest:v001
      depends_on:
        - pgdatabase
      command: >
        ingest_zones.py
        --pg-user=root
        --pg-pass=root
        --pg-host=pgdatabase
        --pg-port=5432
        --pg-db=ny_taxi
      profiles:
        - ingest

  ingest_green:
      image: taxi_ingest:v001
      depends_on:
        - pgdatabase
      command: >
        ingest_data_3.py
        --pg-user=root
        --pg-pass=root
        --pg-host=pgdatabase
        --pg-port=5432
        --pg-db=ny_taxi
      profiles:
        - ingest

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: